spring.application.name=connections-service

server.port=${SERVER_PORT}

server.servlet.context-path=/connections

eureka.instance.prefer-ip-address=true

spring.neo4j.uri=${SPRING_NEO4J_URL}
spring.neo4j.authentication.username=${SPRING_NEO4J_AUTHENTICATION_USERNAME}
spring.neo4j.authentication.password=${SPRING_NEO4J_AUTHENTICATION_PASSWORD}
